version: '3.8'

services:
  bookstore-api:
    container_name: bookstore-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - bookstore-network
    stdin_open: true
    tty: true
    environment:
      - MONGO_URL=mongo
    entrypoint: ["/app/start.sh"]

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge